[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "camera=(), geolocation=(), microphone=(), autoplay=(), fullscreen=(), picture-in-picture=(), sync-xhr=(), encrypted-media=()"
    Strict-Transport-Security = "max-age=15768000; includeSubdomains; preload"
    X-Frame-Options = "DENY"
    X-Xss-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'; base-uri 'self'; form-action 'none'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; object-src 'none'; script-src 'self' 'unsafe-inline'; script-src-elem 'self'; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline'; worker-src 'self' blob:"